% NOTE:
% Before you begin, it is imperative that you import the "day" variable.
% Instructions for how to do this can be found in the README, which should
% be read before running this script. Thanks!

% Running Original, Colinear, Lasso and Ridge Regressions:
[ multiple_reg_mdl, CI, adj_r, mean_num_bikers, mean_peak, mean_low ] ...
    = InitialRegression( day );

[ noncollinear_predictors, collinear_multiple_reg_mdl, CI_collinear, ...
    collinear_adj_r, collinear_mean_num_bikers, collinenar_mean_peak, ...
    collinear_mean_low ] = CollinearRegression( day );

[ lasso_betas, lasso_multiple_reg_mdl, CI_lasso, lasso_adj_r, ...
    lasso_mean_num_bikers, lasso_mean_peak, lasso_mean_low ] = ...
    LassoRegression( day );

[ collinear_lasso_betas, multiple_reg_mdl_collinear_lasso, ...
    CI_collinear_lasso, adj_r_collinear_lasso, ...
    mean_num_bikers_collinear_lasso, mean_peak_collinear_lasso, ...
    mean_low_collinear_lasso ] = LassoRegressionCollinear( ...
    noncollinear_predictors, day(:,14) );

[ ridge_betas, ridge_multiple_reg_mdl, CI_ridge, ridge_adj_r, ...
    ridge_mean_num_bikers, ridge_mean_peak, ridge_mean_low ] = ...
    RidgeResgression( day );
